insert into SrcVal(SrcCde, SrcTxt) values (1, "Holy Grail");
insert into SrcVal(SrcCde, SrcTxt) values (2, "This is Spinal Tap");
insert into SrcVal(SrcCde, SrcTxt) values (3, "Life of Brian");
insert into SrcVal(SrcCde, SrcTxt) values (4, "Monty Python's Flying Circus");
insert into SrcVal(SrcCde, SrcTxt) values (5, "When Harry Met Sally");
insert into SrcVal(SrcCde, SrcTxt) values (6, "American Beauty");
insert into SrcVal(SrcCde, SrcTxt) values (7, "Yes, Prime Minister");
insert into SrcVal(SrcCde, SrcTxt) values (8, "Star Wars:  A New Hope");
insert into SrcVal(SrcCde, SrcTxt) values (9, "Yes, Minister");
insert into SrcVal(SrcCde, SrcTxt) values (10, "Babylon 5");
insert into SrcVal(SrcCde, SrcTxt) values (11, "Seinfeld");
insert into SrcVal(SrcCde, SrcTxt) values (12, "The Princess Bride");
insert into SrcVal(SrcCde, SrcTxt) values (13, "There's Something About Mary");
insert into SrcVal(SrcCde, SrcTxt) values (14, "Sleepless in Seattle");
insert into SrcVal(SrcCde, SrcTxt) values (15, "The Philadelphia Story");
insert into SrcVal(SrcCde, SrcTxt) values (16, "John Lennon");
insert into SrcVal(SrcCde, SrcTxt) values (17, "Charade");
insert into SrcVal(SrcCde, SrcTxt) values (18, "Notorious");
insert into SrcVal(SrcCde, SrcTxt) values (19, "Casablanca");
insert into SrcVal(SrcCde, SrcTxt) values (20, "Office Space");
insert into SrcVal(SrcCde, SrcTxt) values (21, "Manhattan Murder Mystery");
insert into SrcVal(SrcCde, SrcTxt) values (22, "Thank You For Smoking");
insert into SrcVal(SrcCde, SrcTxt) values (23, "Soapdish");
insert into SrcVal(SrcCde, SrcTxt) values (24, "Four Weddings And A Funeral");
insert into SrcVal(SrcCde, SrcTxt) values (25, "Miss Congeniality");
insert into SrcVal(SrcCde, SrcTxt) values (28, "Clerks");
insert into SrcVal(SrcCde, SrcTxt) values (29, "America's Sweethearts");
insert into SrcVal(SrcCde, SrcTxt) values (30, "The Simpsons");
insert into SrcVal(SrcCde, SrcTxt) values (31, "A Beautiful Mind");
insert into SrcVal(SrcCde, SrcTxt) values (32, "Indiscreet");
insert into SrcVal(SrcCde, SrcTxt) values (33, "Fawlty Towers");
insert into SrcVal(SrcCde, SrcTxt) values (34, "Frasier");
insert into SrcVal(SrcCde, SrcTxt) values (36, "A Fish Called Wanda");
insert into SrcVal(SrcCde, SrcTxt) values (38, "Blondie");
insert into SrcVal(SrcCde, SrcTxt) values (39, "As Good As It Gets");
insert into SrcVal(SrcCde, SrcTxt) values (40, "Kids in the Hall");
insert into SrcVal(SrcCde, SrcTxt) values (41, "The Simpsons Movie");
insert into SrcVal(SrcCde, SrcTxt) values (42, "The Honeymooners");
insert into SrcVal(SrcCde, SrcTxt) values (43, "Roxanne");
insert into SrcVal(SrcCde, SrcTxt) values (44, "Cheers");
insert into SrcVal(SrcCde, SrcTxt) values (45, "Juno");
insert into SrcVal(SrcCde, SrcTxt) values (46, "Raising Arizona");
insert into SrcVal(SrcCde, SrcTxt) values (47, "Fight Club");
insert into SrcVal(SrcCde, SrcTxt) values (1047, "Zoolander");
insert into SrcVal(SrcCde, SrcTxt) values (1048, "My Big Fat Greek Wedding");
insert into SrcVal(SrcCde, SrcTxt) values (1049, "The Social Network");
insert into SrcVal(SrcCde, SrcTxt) values (1050, "Easy A");
insert into SrcVal(SrcCde, SrcTxt) values (1051, "Modern Family");
insert into SrcVal(SrcCde, SrcTxt) values (1053, "All in the Family");
insert into SrcVal(SrcCde, SrcTxt) values (1054, "The Middle");
insert into SrcVal(SrcCde, SrcTxt) values (1055, "Heartburn");
insert into SrcVal(SrcCde, SrcTxt) values (1056, "The Pink Panther Strikes Again");
insert into SrcVal(SrcCde, SrcTxt) values (1057, "Cactus Flower");
insert into SrcVal(SrcCde, SrcTxt) values (1058, "Annie Hall");
insert into SrcVal(SrcCde, SrcTxt) values (1059, "This Is 40");
insert into SrcVal(SrcCde, SrcTxt) values (1060, "Sons of Anarchy");
insert into SrcVal(SrcCde, SrcTxt) values (1061, "Get Shorty");
insert into SrcVal(SrcCde, SrcTxt) values (1062, "House");
insert into SrcVal(SrcCde, SrcTxt) values (1063, "Elementary");
insert into SrcVal(SrcCde, SrcTxt) values (1064, "Coming to America");
